CAPTION = "SNAKE"
WIDTH = 400
HEIGHT = 400
SCREEN_SIZE = (WIDTH, HEIGHT)

BACKGROUND_COLOR = (0, 0, 0)  # BLACK
PLAYBOARD_BACKGROUND_COLOR = (255, 255, 255)  # WHITE
FPS = 60

CELL_SIZE = 80
N_WIDTH = WIDTH // CELL_SIZE
N_HEIGHT = HEIGHT // CELL_SIZE
MATRIX_SIZE = (N_WIDTH, N_HEIGHT, 4)


LEARNING_RATE = 0.1
GAMMA = 0.9
EPSILON = 0.2

DEFAULT_APPLE_X = N_WIDTH - 1
DEFAULT_APPLE_Y = N_HEIGHT - 1
DEFAULT_APPLE_COLOR = (255, 0, 0)  # RED

DEFAULT_SNAKE_X = 0
DEFAULT_SNAKE_Y = 0
DEFAULT_SNAKE_COLOR = (0, 255, 0)  # GREEN

DEFAULT_GRID_X = N_WIDTH
DEFAULT_GRID_Y = N_HEIGHT
DEFAULT_GRID_COLOR = (100, 100, 100)  # GRAY
